# vim: set tabstop=2 softtabstop=2 shiftwidth=2 expandtab:

name: Build main branch

on:
  pull_request:
    branches: [main]
    types: [closed]
  push:
    branches: [main]
  workflow_call:

jobs:
  build:
    name: Build wheel(s) and packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"
      - name: Install build tools
        run: python -m pip install build
      - name: Build wheel(s) and packages
        run: python -m build .
      - name: Upload built packages
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: dist/*.*
